spring:
  application:
    name: microservice-probe
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}?schema=${DATABASE_SCHEMA:ms-probe}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:postgres}
  sql:
    init:
      mode: always

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
