spring:
  application:
    name: microservice-probe
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=ms-probe
    username: postgres
    password: abc123
  sql:
    init:
      mode: always

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
